# What is Scikit-learn Package?

Scikit-learn (formerly scikits.learn and also known as sklearn) is a free software machine learning library for the Python programming language.It features various classification, regression and clustering algorithms including support vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy.

## Important features of scikit-learn:

● Simple  and efficient tools for data mining and data analysis. It features various classification, regression and clustering algorithms including support vector machines, random forests, gradient boosting, k-means, etc.

● Accessible to everybody and reusable in various contexts.

● Built on the top of NumPy, SciPy, and matplotlib.

●Open source, commercially usable – BSD license.


In this article, we are going to see how we can easily build a machine learning model using scikit-learn.

### Installing
Before installing scikit-learn, ensure that you have NumPy and SciPy installed. Once you have a working installation of NumPy and SciPy, the easiest way to install scikit-learn is using pip:

#### pip install -U scikit-learn

Let us get started with the modeling process now.

### Step 1: Load a dataset

A dataset is nothing but a collection of data. A dataset generally has two main components:

● Features: (also known as predictors, inputs, or attributes) they are simply the variables of our data. They can be more than one and hence represented by a feature matrix (‘X’ is a common notation to represent feature matrix). A list of all the feature names is termed as feature names.

● Response: (also known as the target, label, or output) This is the output variable depending on the feature variables. We generally have a single response column and it is represented by a response vector (‘y’ is a common notation to represent response vector). All the possible values taken by a response vector is termed as target names.

● Loading exemplar dataset: scikit-learn comes loaded with a few example datasets like the iris and digits datasets for classification and the boston house prices dataset for regression.

In [1]:
# load the iris dataset as an example 
from sklearn.datasets import load_iris 
iris = load_iris()

In [2]:
# store the feature matrix (X) and response vector (y) 
X = iris.data 
y = iris.target

In [3]:
# store the feature and target names 
feature_names = iris.feature_names 
target_names = iris.target_names 

In [4]:
# printing features and target names of our dataset 
print("Feature names:", feature_names) 
print("Target names:", target_names) 

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [5]:
# X and y are numpy arrays 
print("\nType of X is:", type(X)) 
  
# printing first 5 input rows 
print("\nFirst 5 rows of X:\n", X[:5])


Type of X is: <class 'numpy.ndarray'>

First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


# Update Coming Soon...............