#  Python Numpy

## what is Numpy Package ? 
Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

###                Arrays in Numpy

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

### Creating a Numpy Array
Arrays in Numpy can be created by multiple ways, with various number of Ranks, defining the size of the Array. Arrays can also be created with the use of various data types such as lists, tuples, etc. The type of the resultant array is deduced from the type of the elements in the sequences.

In [1]:
# Python program for
# Creation of Arrays
import numpy as np

In [2]:
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

Array with Rank 1: 
 [1 2 3]


In [3]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]


In [4]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array created using passed tuple:
 [1 3 2]


### Accessing the array Index
In a numpy array, indexing or accessing the array index can be done in multiple ways. To print a range of an array, slicing is done. Slicing of an array is defining a range in a new array which is used to print a range of elements from the original array. Since, sliced array holds a range of elements of the original array, modifying content with the help of sliced array modifies the original array content.

In [5]:
# Python program to demonstrate
# indexing in numpy array
import numpy as np

In [6]:
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [7]:
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [8]:
# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


### Basic Array Operations
In numpy, arrays allow a wide range of operations which can be performed on a particular array or a combination of Arrays. These operation include some basic Mathematical operation as well as Unary and Binary operations.

In [9]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])

In [10]:
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

In [11]:
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)

Adding 1 to every element: [[2 3]
 [4 5]]


In [12]:
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)


Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]


In [13]:
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())


Sum of all array elements:  10


In [14]:
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


### More on Numpy Arrays

● Basic Array Operations in Numpy

● Advanced Array Operations in Numpy


● Basic Slicing and Advanced Indexing in NumPy Python

### Data Types in Numpy
Every Numpy array is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. Every ndarray has an associated data type (dtype) object. This data type object (dtype) provides information about the layout of the array. The values of an ndarray are stored in a buffer which can be thought of as a contiguous block of memory bytes which can be interpreted by the dtype object. Numpy provides a large set of numeric datatypes that can be used to construct arrays. At the time of Array creation, Numpy tries to guess a datatype, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

### Constructing a Datatype Object
In Numpy, datatypes of Arrays need not to be defined unless a specific datatype is required. Numpy tries to guess the datatype for Arrays which are not predefined in the constructor function.

In [15]:
# Integer datatype
# guessed by Numpy
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype) 

Integer Datatype: 
int32


In [16]:
# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  


Float Datatype: 
float64


In [17]:
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int64


### Math Operations on DataType array
In Numpy arrays, basic mathematical operations are performed element-wise on the array. These operations are applied both as operator overloads and as functions. Many useful functions are provided in Numpy for performing computations on Arrays such as sum: for addition of Array elements, T: for Transpose of elements, etc.

In [18]:
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
  

In [19]:
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 

In [21]:
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]


In [22]:
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)


Addition of Array elements: 
19.0


In [23]:
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)


Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [24]:
# Transpose of Array
# using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)


Transpose of Array: 
[[4. 2.]
 [7. 6.]]


### More on Numpy Data Type

● Data type Object (dtype) in NumPy

#### Methods in Numpy

all()
any()
take()
put()
apply_along_axis()
apply_over_axes()
argmin()
argmax()
nanargmin()
nanargmax()
amax()
amin()
insert()
delete()
append()
around()
flip()
fliplr()
flipud()
triu()
tril()
tri()
empty()
empty_like()
zeros()
zeros_like()
ones()
ones_like()
full_like()
diag()
diagflat()
diag_indices()
asmatrix()
bmat()
eye()
roll()
identity()
arange()
place()
extract()
compress()
rot90()
tile()
reshape()
ravel()
isinf()
isrealobj()
isscalar()
isneginf()
isposinf()
iscomplex()
isnan()
iscomplexobj()
isreal()
isfinite()
isfortran()
exp()
exp2()
fix()
hypot()
absolute()
ceil()
floor()
degrees()
radians()
npv()
fv()
pv()
power()
float_power()
log()
log1()
log2()
log10()
dot()
vdot()
trunc()
divide()
floor_divide()
true_divide()
random.rand()
random.randn()
ndarray.flat()
expm1()
bincount()
rint()
equal()
not_equal()
less()
less_equal()
greater()
greater_equal()
prod()
square()
cbrt()
logical_or()
logical_and()
logical_not()
logical_xor()
array_equal()
array_equiv()
sin()
cos()
tan()
sinh()
cosh()
tanh()
arcsin()
arccos()
arctan()
arctan2()

## Arithmetic Array Operations:

In [25]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [26]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [27]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [28]:

# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [29]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [30]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [31]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


#### Statistical Methods, Sorting, and

#### Set Operations:


#### Basic Statistical Operations: 

In [32]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[-0.98823754 -3.89466448  3.66803557 -3.66836489  3.13401044]
 [12.42015974  8.94186828  9.81416282 -4.90348388  6.05095707]]


In [33]:
# compute the mean for all elements
print(arr.mean())

3.057444313745164


In [34]:

# compute the means by row
print(arr.mean(axis = 1))

[-0.34984418  6.46473281]


In [35]:

# compute the means by column
print(arr.mean(axis = 0))

[ 5.7159611   2.5236019   6.7410992  -4.28592439  4.59248376]


In [36]:

# sum all the elements
print(arr.sum())

30.574443137451638


In [37]:
# compute the medians
print(np.median(arr, axis = 1))

[-0.98823754  8.94186828]


#### Sorting:

In [38]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[ 0.07146995 -0.28602378 -1.67198311 -1.08111735  2.09176577  0.12796216
  1.31356868 -0.79805187  2.50935128  0.08300418]


In [39]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.67198311 -1.08111735 -0.79805187 -0.28602378  0.07146995  0.08300418
  0.12796216  1.31356868  2.09176577  2.50935128]

[ 0.07146995 -0.28602378 -1.67198311 -1.08111735  2.09176577  0.12796216
  1.31356868 -0.79805187  2.50935128  0.08300418]


In [40]:

# inplace sorting
unsorted.sort() 

print(unsorted)

[-1.67198311 -1.08111735 -0.79805187 -0.28602378  0.07146995  0.08300418
  0.12796216  1.31356868  2.09176577  2.50935128]


#### Finding Unique elements:

In [41]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


#### Set Operations with np.array data type :

In [42]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [43]:
print( np.intersect1d(s1, s2) )

['bulb' 'chair']


In [44]:

print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [45]:

print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

['desk']


In [46]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]


#### Broadcasting:

In [47]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [49]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [50]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [51]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [53]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Example from the slides:

In [54]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [56]:
# add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


#### Speedtest: ndarrays vs lists

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [57]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [58]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [59]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.001045 seconds


In [60]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [61]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.057786 seconds


### Read or Write to Disk:
Binary Format :

In [62]:
x = np.array([ 23.23, 24.24] )

In [63]:
np.save('an_array', x)

In [64]:
np.load('an_array.npy')

array([23.23, 24.24])

 #### Text Format:

In [66]:
np.savetxt('array.txt', X=x, delimiter=',')

In [67]:
!cat array.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.


In [68]:

np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

### Additional Common ndarray Operations



Dot Product on Matrices and Inner Product on Vectors:

In [69]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [70]:

# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


#### Sum:

In [71]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

66


In [72]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [73]:
print(np.sum(ex1, axis=1))  # rowwise sum

[23 43]


### Element-wise Functions:

For example, let's compare two arrays values to get the maximum of each.

In [74]:
# random array
x = np.random.randn(8)
x

array([ 0.43237603, -0.70918882, -0.27107786,  0.62689432, -0.38940094,
        1.01626746,  0.68647582, -1.54969724])

In [75]:
# another random array
y = np.random.randn(8)
y

array([-0.55031019,  1.43115846,  0.07780906,  2.49211138, -0.15953708,
       -0.54679971,  1.32062722,  1.24892684])

In [76]:
# returns element wise maximum between two arrays

np.maximum(x, y)

array([ 0.43237603,  1.43115846,  0.07780906,  2.49211138, -0.15953708,
        1.01626746,  1.32062722,  1.24892684])

#### Reshaping array: 

In [78]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [79]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### Transpose:

In [80]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

#### Indexing using where(): 

In [81]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [82]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [83]:
mat = np.random.rand(5,5)
mat

array([[0.65775654, 0.35202745, 0.93116944, 0.19952961, 0.36677332],
       [0.16101492, 0.63093601, 0.63981166, 0.3498245 , 0.90994216],
       [0.75194287, 0.24241733, 0.50757426, 0.78859435, 0.92985679],
       [0.43518679, 0.10807067, 0.86216899, 0.20002059, 0.84964507],
       [0.18187896, 0.81680503, 0.37961501, 0.16335777, 0.87966243]])

In [84]:
np.where( mat > 0.5, 1000, -1)

array([[1000,   -1, 1000,   -1,   -1],
       [  -1, 1000, 1000,   -1, 1000],
       [1000,   -1, 1000, 1000, 1000],
       [  -1,   -1, 1000,   -1, 1000],
       [  -1, 1000,   -1,   -1, 1000]])

#### any" or "all" conditionals: 

In [85]:
arr_bools = np.array([ True, False, True, True, False ])

In [86]:
arr_bools.any()

True

In [87]:
arr_bools.all()

False

#### Random Number Generation: 

In [88]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-0.20930383  1.1817029  -1.08682346  0.12769727  0.96755353]


In [89]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[19 17  5 38]


In [90]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([19, 38, 17,  5])

In [91]:
np.random.uniform(size=4) #uniform distribution

array([0.97388887, 0.81634125, 0.39503209, 0.87849288])

In [92]:
np.random.normal(size=4) #normal distribution

array([ 1.75579064,  0.8644224 ,  0.38618344, -0.02562121])

#### Merging data sets:

In [93]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[24  9]
 [17 32]]

[[12 10]
 [18 14]]


In [94]:
np.vstack((K,M))

array([[24,  9],
       [17, 32],
       [12, 10],
       [18, 14]])

In [95]:
np.hstack((K,M))

array([[24,  9, 12, 10],
       [17, 32, 18, 14]])

In [96]:
np.concatenate([K, M], axis = 0)

array([[24,  9],
       [17, 32],
       [12, 10],
       [18, 14]])

In [97]:
np.concatenate([K, M.T], axis = 1)

array([[24,  9, 12, 18],
       [17, 32, 10, 14]])

## Mathematical Functions
Numpy offers a range of powerful Mathematical functions. This is one of the reasons why the library is popular in quantitative fields. Additionally, a number of libraries are built on top of Numpy due to the fact that it has a rich set of mathematical features.
### Add, Subtract, Multiply, Divide, Power, Mod
To perform basic arithmetic functions on two arrays a and b:

In [98]:
a = [1,2]
b= [3,4]
c = np.add(a, b)
c = np.subtract(a, b)
c = np.multiply(a, b)
c = np.divide(a, b)
c = np.power(a, b) 
c = np.power(a, 2)
#to get remainder
c= np.mod(a, b)
c = np.remainder(a, b)

## Rounding, Ceil, Floor
To change the precision of all elements of an array: 

In [ ]:
np.around(array, 4) # 4dp
np.ceil(array) #1.8 will become 2
np.floor(array) #1.8 will become 1

### Trigonometric

In [ ]:
array = [0, 1]
np.sin(array)
np.cos(array)
np.tan(array)
np.arcsin(array)
np.arccos(array)
np.arctan(array)

 A number of complex number functions can also be applied such as getting real or imaginary parts of an array with complex numbers.
 
 
### Statistical
There are also a large number of statistical functions available:

In [ ]:
a = [1,2]
np.amin(a, 0) #min in the axis
np.amax(a, 0) #max in the axis
np.percentile(a, 10)
#Additionally, following functions are available:
np.median(a)
np.std(a)
np.average(a)
np.mean(a)
np.var(a)

### Algebra
Numpy contains a module which is known as linalg. 

It is rich with a number of algebraic functions: 

In [ ]:
1. dot() #dot product of two arrays
2. inner() #inner product of two arrays
3. determinant() #determinant of an array
4. solve() #solves matrix equation
5. inv() #inverse of matrix
6. matmul() #matrix product of two arrays

## Notes On Numba
We can use Numba to create fast functions for Numpy.

Numba functions are essentially pure Python functions.

The trick is to use nb.jit(func) to compile a function into its faster Numba version. We can also use @numba.vectorize decorator on the function to compile the code into NumPy ufunc.

Although Numba does not support all Python code, it can handle most of the numerical algorithms that are written in pure Python.

# Summary
This article provided an overview of the core functionalities of the NumPy library. Since NumPy was incorporated with the features of Numarray in 2005, it has gained huge popularity and is considered to be one of the key Python libraries to use.